// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVx0FIx4sDcpJL5Js-9AP2aiEdEdmY4OA',
    appId: '1:547790910674:web:86e1e14e90abc80625290b',
    messagingSenderId: '547790910674',
    projectId: 'fasum-ulhad',
    authDomain: 'fasum-ulhad.firebaseapp.com',
    storageBucket: 'fasum-ulhad.appspot.com',
    measurementId: 'G-58QCXBQ4XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCckqSsblsLf8BUXdOXGwHLrkhNNBXduPw',
    appId: '1:547790910674:android:e3d51ee76413d67225290b',
    messagingSenderId: '547790910674',
    projectId: 'fasum-ulhad',
    storageBucket: 'fasum-ulhad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz9luYELEbrbcDKfr3txItG_-iiZTySd4',
    appId: '1:547790910674:ios:8af9dc8887bccfb925290b',
    messagingSenderId: '547790910674',
    projectId: 'fasum-ulhad',
    storageBucket: 'fasum-ulhad.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz9luYELEbrbcDKfr3txItG_-iiZTySd4',
    appId: '1:547790910674:ios:8af9dc8887bccfb925290b',
    messagingSenderId: '547790910674',
    projectId: 'fasum-ulhad',
    storageBucket: 'fasum-ulhad.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVx0FIx4sDcpJL5Js-9AP2aiEdEdmY4OA',
    appId: '1:547790910674:web:9f24cb762283cfb125290b',
    messagingSenderId: '547790910674',
    projectId: 'fasum-ulhad',
    authDomain: 'fasum-ulhad.firebaseapp.com',
    storageBucket: 'fasum-ulhad.appspot.com',
    measurementId: 'G-NPB570D2H5',
  );

}